### ISSUE TITLE
Path to templates not works

### ISSUE THREAD

**Issue by tba6440** [nimius/workshops#3]
Tried to change the paths for templates in TS constants first. 
eg: 
plugin.tx_workshops.view.templateRootPath = fileadmin/mytemplate/Templates/

after it not seems to work I tried it in TS setup 
plugin.tx_workshops,view.templateRootPath = fileadmin/mytemplate/Templates/

No of both setting will change the path to the templates. 
In FE I still get the output from EXT:workshops/Resources/Private/Templates/

Typo3 is 7.6.16

**Comment by pduersteler** [comment]
Hi

Your TypoScript path (not the constant) seems to have a typo in it; There is a comma instead of a point.

I just checked the TypoScript, and the modern way to go would be to define `templateRootPaths`, e.g. like this:

```
templateRootPaths {
	0 = EXT:workshops/Resources/Private/Templates/
	1 = EXT:your_theme_extension/Resources/Private/Templates/Extensions/Workshops/
}
```

I'm going to update the default TypoScript to reflect this; However, using your own templates works, as we're using workshops in several instances with custom templates per instance.
